import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Allert",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="kr">
            <body> {children} </body>
        </html>
    );
}

